server:
   port: 5555
spring:
   application:
      name: cloud-zuul-service
ribbon:  
   ReadTimeout: 30000
   ConnectTimeout: 30000
zuul:
   sensitiveHeaders: Access-Control-Allow-Origin,Cookie,Set-Cookie  #this is Head blacklist
   ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
   ignored-services: '*'
   prefix: /api
   host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 30000
   routes:
      cloud-user-service: /cloud-user-service/**   #wait a moment
      cloud-auth2-service: /cloud-auth2-service/**
      cloud-buyer-service: /cloud-buyer-service/**
      cloud-seller-service: /cloud-seller-service/**
      cloud-shared-service: /cloud-shared-service/**
      cloud-admin-service: /cloud-admin-service/**
#      user-service:   #
#         path: /cloud-simple-service/**
#         url: http://localhost:8081/
   #
   add-proxy-headers: true
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeout-in-milliseconds: 30000
eureka:
   instance:
      preferIpAddress: true
      client: 
         registerWithEureka: true
         fetchRegistry: true
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/
logging:
   level:
      com.netflix: DEBUG
      com.bruin.cloud.zuul.filters: DEBUG